// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: server_to_node.proto

package server_to_node

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcctName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AcctName) Reset() {
	*x = AcctName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctName) ProtoMessage() {}

func (x *AcctName) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctName.ProtoReflect.Descriptor instead.
func (*AcctName) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{0}
}

func (x *AcctName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Acct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Passwd   string `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
}

func (x *Acct) Reset() {
	*x = Acct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acct) ProtoMessage() {}

func (x *Acct) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acct.ProtoReflect.Descriptor instead.
func (*Acct) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{1}
}

func (x *Acct) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Acct) GetPasswd() string {
	if x != nil {
		return x.Passwd
	}
	return ""
}

type AcctInf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateOf_Creation string   `protobuf:"bytes,1,opt,name=date_of_Creation,json=dateOfCreation,proto3" json:"date_of_Creation,omitempty"`
	Name            string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastPost        string   `protobuf:"bytes,3,opt,name=last_post,json=lastPost,proto3" json:"last_post,omitempty"`
	Posts           []string `protobuf:"bytes,4,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *AcctInf) Reset() {
	*x = AcctInf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctInf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctInf) ProtoMessage() {}

func (x *AcctInf) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctInf.ProtoReflect.Descriptor instead.
func (*AcctInf) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{2}
}

func (x *AcctInf) GetDateOf_Creation() string {
	if x != nil {
		return x.DateOf_Creation
	}
	return ""
}

func (x *AcctInf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AcctInf) GetLastPost() string {
	if x != nil {
		return x.LastPost
	}
	return ""
}

func (x *AcctInf) GetPosts() []string {
	if x != nil {
		return x.Posts
	}
	return nil
}

type AcctSucc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AcctSucc) Reset() {
	*x = AcctSucc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcctSucc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcctSucc) ProtoMessage() {}

func (x *AcctSucc) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcctSucc.ProtoReflect.Descriptor instead.
func (*AcctSucc) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{3}
}

func (x *AcctSucc) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date   string    `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Author *AcctName `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Body   string    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{4}
}

func (x *Post) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Post) GetAuthor() *AcctName {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PostSucc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PostSucc) Reset() {
	*x = PostSucc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostSucc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSucc) ProtoMessage() {}

func (x *PostSucc) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSucc.ProtoReflect.Descriptor instead.
func (*PostSucc) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{5}
}

func (x *PostSucc) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{6}
}

func (x *Page) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type Feed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Posts []*Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (x *Feed) Reset() {
	*x = Feed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_to_node_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_server_to_node_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_server_to_node_proto_rawDescGZIP(), []int{7}
}

func (x *Feed) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_server_to_node_proto protoreflect.FileDescriptor

var file_server_to_node_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74,
	0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x04, 0x41, 0x63, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x64, 0x22, 0x7b, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x12,
	0x28, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6f, 0x66, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f,
	0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73,
	0x22, 0x25, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x61, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x06,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x25, 0x0a, 0x09, 0x50, 0x6f,
	0x73, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x32, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x6f, 0x73,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x05,
	0x70, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x32, 0x0a, 0x04, 0x46, 0x65, 0x65, 0x64, 0x12, 0x2a, 0x0a,
	0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x32, 0x8d, 0x02, 0x0a, 0x0c, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x09, 0x41, 0x63,
	0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x22, 0x00, 0x12, 0x3e,
	0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x74, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x41, 0x63, 0x63, 0x74, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x5f, 0x66, 0x65, 0x65, 0x64, 0x12, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x22, 0x00, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x72, 0x65, 0x65, 0x7a, 0x79, 0x39, 0x35,
	0x2f, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_to_node_proto_rawDescOnce sync.Once
	file_server_to_node_proto_rawDescData = file_server_to_node_proto_rawDesc
)

func file_server_to_node_proto_rawDescGZIP() []byte {
	file_server_to_node_proto_rawDescOnce.Do(func() {
		file_server_to_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_to_node_proto_rawDescData)
	})
	return file_server_to_node_proto_rawDescData
}

var file_server_to_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_server_to_node_proto_goTypes = []interface{}{
	(*AcctName)(nil), // 0: server_to_node.Acct_name
	(*Acct)(nil),     // 1: server_to_node.Acct
	(*AcctInf)(nil),  // 2: server_to_node.Acct_inf
	(*AcctSucc)(nil), // 3: server_to_node.Acct_succ
	(*Post)(nil),     // 4: server_to_node.Post
	(*PostSucc)(nil), // 5: server_to_node.Post_succ
	(*Page)(nil),     // 6: server_to_node.Page
	(*Feed)(nil),     // 7: server_to_node.Feed
}
var file_server_to_node_proto_depIdxs = []int32{
	0, // 0: server_to_node.Post.author:type_name -> server_to_node.Acct_name
	4, // 1: server_to_node.Page.posts:type_name -> server_to_node.Post
	4, // 2: server_to_node.Feed.posts:type_name -> server_to_node.Post
	0, // 3: server_to_node.Backend_info.Acct_info:input_type -> server_to_node.Acct_name
	4, // 4: server_to_node.Backend_info.Send_post:input_type -> server_to_node.Post
	1, // 5: server_to_node.Backend_info.Add_acct:input_type -> server_to_node.Acct
	4, // 6: server_to_node.Backend_info.Get_feed:input_type -> server_to_node.Post
	2, // 7: server_to_node.Backend_info.Acct_info:output_type -> server_to_node.Acct_inf
	5, // 8: server_to_node.Backend_info.Send_post:output_type -> server_to_node.Post_succ
	3, // 9: server_to_node.Backend_info.Add_acct:output_type -> server_to_node.Acct_succ
	7, // 10: server_to_node.Backend_info.Get_feed:output_type -> server_to_node.Feed
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_server_to_node_proto_init() }
func file_server_to_node_proto_init() {
	if File_server_to_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_to_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Acct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctInf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcctSucc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostSucc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_to_node_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_to_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_to_node_proto_goTypes,
		DependencyIndexes: file_server_to_node_proto_depIdxs,
		MessageInfos:      file_server_to_node_proto_msgTypes,
	}.Build()
	File_server_to_node_proto = out.File
	file_server_to_node_proto_rawDesc = nil
	file_server_to_node_proto_goTypes = nil
	file_server_to_node_proto_depIdxs = nil
}
